services:
  application:
    build: ./
    container_name: application
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/qa-service/configs/config.yaml
    depends_on:
      - migrations
      - database
  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=qa-service-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db_data:/var/lib/postgres/data
    restart: always
  migrations:
    image: golang:1.24.3-alpine
    volumes:
      - ./migrations:/migrations
    depends_on:
      - database
    entrypoint: ["/bin/sh", "-c"]
    command: ["apk add --no-cache postgresql-client git; go install github.com/pressly/goose/v3/cmd/goose@v3.11.0; /go/bin/goose -dir /migrations postgres \"user=admin password=admin host=database port=5432 dbname=qa-service-db sslmode=disable\" up"]
    restart: "no"
volumes:
  db_data: